name: e2e UI playwright
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
        steps:
      - name: Get timestamp
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M-%S')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.AUTOTEST_GCLOUD_CREDENTIALS }}
          instance: thor-ci-concept:europe-central2:thor-pg-dev1
      - name: Install dependencies
        run: cd tests && npm ci
      - name: Install Playwright binary
        run: cd tests && npx playwright install chromium --with-deps
      - name: Set local variables
        run: |
          echo "BASE_URL=https://tp-admin.tp-develop.com" >> $GITHUB_ENV
          echo "DB_SCHEMA=tp_admin" >> $GITHUB_ENV
      - name: Run tests
        id: test
        run: cd tests && npx playwright test
        env:
          BASE_USER: ${{ secrets.AUTOTEST_BASE_USER }}
          BASE_PASSWORD: ${{ secrets.AUTOTEST_BASE_PASSWORD }}
          BASE_URL: ${{ env.BASE_URL }}
          DB_SCHEMA: ${{ env.DB_SCHEMA }}
          DATABASE_CONNECTION: postgresql://${{ secrets.AUTOTEST_DB_USER }}:${{ secrets.AUTOTEST_DB_PASSWORD}}@localhost:5432/micros_develop_2?currentSchema=${{ env.DB_SCHEMA }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report-${{ steps.date.outputs.timestamp }}
          path: tests/playwright-report/
          retention-days: 15
