name: db connect
on:
  # push:
  #   branches: [main, master]
  workflow_dispatch:
    inputs:
      scope:
        description: "Test scope"
        required: true
        default: "@regression"
        type: choice
        options:
          - "@regression"
          - "@smoke"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Check scope
        run: |
          echo "bla bla ${{ github.event.inputs.scope }}"
      - name: create cloud sql proxy credentials
        run: |
          echo "The GitHub Action Secret will be masked:  " 
          echo ${{ secrets.BASE_USER }}
          echo "Trick to echo GitHub Actions Secret:  " 
          echo ${{secrets.BASE_USER}} | sed 's/./& /g'
      - uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.CLOUD_SQL_AUTH }}
          instance: thor-ci-concept:europe-central2:thor-pg-dev1
      - name: Install dependencies
        run: cd tests && npm ci
      - name: Install Playwright
        run: cd tests && npx playwright install --with-deps
      - name: Run Playwright tests
        env: BASE_USER:${{secrets.BASE_USER}}
        run: cd tests && npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30
